### ISSUE TITLE
BaselineOfElasticsearch renamed the 'Core' and 'Tests' groups, breaking loading

### ISSUE THREAD

**Issue by pdebruic** [newapplesho/elasticsearch-smalltalk#2]
Because the new ConfigurationOfElasticsearch on SS3 is pulling in the BaselineOfElasticsearch from this repo it would nice if you added a 'Core' and 'Test' group so users (although we may be the only two ;) )  didn't have to go and change all the old configs that reference them.

**Comment by newapplesho** [comment]
Let me think about it.
